image: node:6.9.1

before_script:
  - npm i

build_api:
  stage: build
  script:
    - npm run build-api
  artifacts: 
    paths:
      - ./node_modules
      - ./api/dist

build_app:
  stage: build
  script:
    - npm run build-app
  artifacts: 
    paths:
      - ./temp-client/dist

test_unit_api:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - cd api && npm run test-unit

test_integration_api:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - cd api && npm run test-integration

deploy_production:
  stage: deploy
  variables:
    NODE_ENV: "production"
  script:
    - apt-get update -yq
    - apt-get install -y ruby
    - gem install dpl
    - dpl --provider=heroku --strategy=git --username=$HEROKU_USER --password=$HEROKU_PASS --app=$HEROKU_APP --api-key=$HEROKU_PRODUCTION_API_KEY
  only: 
    - master