image: node:6.9.1

build_api:
  stage: build
  cache: 
    paths:
      - ./api/node_modules
  script:
    - cd ./api && npm i && ./node_modules/.bin/tsc

test_unit_api:
  stage: test
  script:
    - ./api/node_modules/.bin/mocha dist/**/__unit/*

test_integration_api:
  stage: test
  script:
    - ./api/node_modules/.bin/mocha dist/**/__integration/*