image: node:6.9.1

build_api:
  stage: build
  script:
    - cd api && npm i && npm run build
  artifacts: 
    paths:
      - ./api/node_modules

test_unit_api:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - cd api && npm run test-unit

test_integration_api:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - cd api && npm run test-integration

deploy_production:
  stage: deploy
  variables:
    NODE_ENV: "production"
    NODE_BPBP_API_URL: https://pacific-harbor-98514.herokuapp.com/
  script:
    - apt-get update -yq
    - apt-get install -y ruby
    - ruby -v
    - gem -v
    - gem install dpl
    - dpl --provider=heroku --app=bpbp-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only: 
    - master