image: node:6.9.1

build_api:
  stage: build
  cache: 
    paths:
      - ./api/node_modules
  script:
    - cd api && npm i && npm run build

test_unit_api:
  stage: test
  script:
    - cd api && npm run test-unit

test_integration_api:
  stage: test
  script:
    - cd api && npm run test-integration