before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs

build_api:
  - cd ./api && npm i
  - ./node_modules/.bin/tsc

test_unit_api:
  - cd ./api
  - ./node_modules/.bin/mocha dist/**/__unit/*

test_integration_api:
  - cd ./api
  - ./node_modules/.bin/mocha dist/**/__integration/*