// action map for all app actions
const GET_PREZIS_REQUEST = "GET_PREZIS_REQUEST"
const GET_PREZIS_SUCCESS = "GET_PREZIS_SUCCESS"
const GET_PREZIS_FAILURE = "GET_PREZIS_FAILURE"

export {
  GET_PREZIS_REQUEST,
  GET_PREZIS_SUCCESS,
  GET_PREZIS_FAILURE,
}
